FROM node:18-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .



# Set New Relic environment variables inside the image
ENV NEW_RELIC_NO_CONFIG_FILE=true \
    NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_LICENSE_KEY="00baa5b95ba4a9cc5250583ead06f193FFFFNRAL"  \
    NEW_RELIC_APP_NAME="webRTC"



# Start the application with New Relic monitoring
CMD ["npm" , "start"]
